[pytest]
markers =
    not_logged: tests that don't require the DB to have valid tokens
    logged: tests that require the DB to have valid tokens

env =
    CLIENT_ID=
    CLIENT_SECRET=
    REDIRECT_URI=http://localhost:5000/spotify/callback
    NTFY_TOKEN=
    NTFY_TOPIC=
    NTFY_URL=
    ENCRYPTION_KEY=test_key
    DB_PATH=/absulote/path/to/config.db
    REDIS_URL=redis://localhost:6379
